cursor #181c20
cursor_text_color #42474e

foreground            #181c20
background            #f7f9ff
selection_foreground  #ffffff
selection_background  #42a5f5
url_color             #1976d2

color0   #101418
color1   #c7003b
color2   #009d14
color3   #fbee00
color4   #1077dc
color5   #b7dbff
color6   #1976d2
color7   #36383a
color8   #aaaeb2
color9   #fb1e60
color10  #07e724
color11  #fff100
color12  #077df1
color13  #b7dbff
color14  #8ec7ff
color15  #f6faff
